openapi: 3.0.0
info:
  title: My API Documentation
  description: This is the API documentation for my application.
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local server
paths:
  /articles:
    get:
      summary: Get a list of articles
      responses:
        '200':
          description: A list of articles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    content:
                      type: string
  /articles/{id}:
    get:
      summary: Get an article by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single article
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
